src/dump.cpp File Reference
#include list.h
Macros
#define LOG_(...) log_printf(&log_file, __VA_ARGS__)
#define FPRINTF_(...) if (fprintf(file, __VA_ARGS__) == 0) return false
#define BACKGROUND_COLOR \#1f1f1f\
#define FONT_COLOR \#000000\
#define NODE_PREFIX elem_
#define NODE_PARAMS shape=\record\, style=\filled\, fillcolor=\#6e7681\
#define ZERO_NODE_PARAMS shape=\record\, style=\filled\, fillcolor=\#6e7681\, color=yellow
#define PRINT_ERR_(code, descr)
Functions
void list_dump (const List *list, const VarCodeData call_data)
(Use LIST_DUMP macros) Dumps list data to log
bool list_dump_dot (const List *list, char *img_filename)
Dumps list array to dot file.
void list_print_error (const int err_code)
Prints text error to log by error code.
Variables
LogFileData log_file
Macro Definition Documentation
BACKGROUND_COLOR
#define BACKGROUND_COLOR \#1f1f1f\
FONT_COLOR
#define FONT_COLOR \#000000\
FPRINTF_
#define FPRINTF_(...) if (fprintf(file, __VA_ARGS__) == 0) return false
Definition at line 55 of file dump.cpp.
LOG_
#define LOG_(...) log_printf(&log_file, __VA_ARGS__)
Definition at line 5 of file dump.cpp.
NODE_PARAMS
#define NODE_PARAMS shape=\record\, style=\filled\, fillcolor=\#6e7681\
NODE_PREFIX
#define NODE_PREFIX elem_
PRINT_ERR_
#define PRINT_ERR_(code, descr)
Value:
                                    if ((err_code) & List::code) \
                                    log_printf(&log_file, \
                                               HTML_TEXT(HTML_RED("!!! " #code ": " descr "\n")));
Definition at line 150 of file dump.cpp.
ZERO_NODE_PARAMS
#define ZERO_NODE_PARAMS shape=\record\, style=\filled\, fillcolor=\#6e7681\, color=yellow
Function Documentation
list_dump()
void list_dump (const List * list, const VarCodeData call_data)
(Use LIST_DUMP macros) Dumps list data to log
Parameters
list
call_data
Definition at line 9 of file dump.cpp.
                                                              {
    assert(list);
    LOG_(HTML_BEGIN);
    LOG_(" list_dump() called from %s:%d %s\n"
         " %s[%p] initialised in %s:%d %s \n",
         call_data.file, call_data.line, call_data.func,
         list->var_data.name, list,
         list->var_data.file, list->var_data.line, list->var_data.func);
    LOG_(" {\n");
    LOG_(" size = %zd\n", list->size);
    LOG_(" head = %p\n", list->head);
    LOG_(" tail = %p\n", list->tail);
    LOG_(" {\n");
    if (!is_ptr_valid(list->head)) {
        if (!list_is_initialised(list))
            LOG_(HTML_RED(" can't read (invalid pointer)\n"));
        LOG_(" }\n"
             " }\n" HTML_END);
        return;
    }
    LOG_(" "" %*s | %*s | %*s | elem\n", -14, "ptr", -14, "prev", -14, "next");
    ListNode* ptr = list->head;
    ssize_t log_i = 0;
    LIST_FOREACH(*list, ptr, log_i) {
        LOG_(" "" %14p | %14p | %14p | " ELEM_T_PRINTF "\n",
                         ptr, ptr->prev, ptr->next, ptr->elem);
    }
    LOG_(" }\n"
         " }\n" HTML_END);
    char img_filename[log_file.MAX_FILENAME_LEN] = {};
    list_dump_dot(list, img_filename);
    LOG_("<img src=\"../../%s\">\n", img_filename);
}
References ListNode::elem, ELEM_T_PRINTF, VarCodeData::file, VarCodeData::func, List::head, HTML_BEGIN, HTML_END, HTML_RED, is_ptr_valid(), VarCodeData::line, list_dump_dot(), LIST_FOREACH, list_is_initialised(), LOG_, log_file, LogFileData::MAX_FILENAME_LEN, VarCodeData::name, ListNode::next, ListNode::prev, List::size, List::tail, and List::var_data.
list_dump_dot()
bool list_dump_dot (const List * list, char * img_filename)
Dumps list array to dot file.
Parameters
list
img_filename returns image filename
Returns
true
false
Definition at line 56 of file dump.cpp.
                                                         {
    #define BACKGROUND_COLOR "\"#1f1f1f\""
    #define FONT_COLOR "\"#000000\""
    #define NODE_PREFIX "elem_"
    #define NODE_PARAMS "shape=\"record\", style=\"filled\", fillcolor=\"#6e7681\""
    #define ZERO_NODE_PARAMS "shape=\"record\", style=\"filled\", fillcolor=\"#6e7681\", color=yellow"
    assert(list);
    static size_t dot_number = 0;
    char dot_filename[log_file.MAX_FILENAME_LEN] = {};
    size_t str_len = strncat_len(dot_filename, log_file.timestamp_dir, log_file.MAX_FILENAME_LEN);
    snprintf(dot_filename + str_len, log_file.MAX_FILENAME_LEN - str_len,
             "%zd", dot_number);
    str_len = strncat_len(dot_filename, ".dot", log_file.MAX_FILENAME_LEN);
    FILE* file = fopen(dot_filename, "wb");
    if (file == nullptr)
        return false;
    FPRINTF_("digraph List{\n"
             " graph [bgcolor=" BACKGROUND_COLOR "];\n"
             " node[color=white, fontcolor=" FONT_COLOR ", fontsize=14];\n");
    FPRINTF_(NODE_PREFIX "zero [" ZERO_NODE_PARAMS ", label=\" head = %p | "
                                                           "tail = %p\"];\n",
             list->head, list->tail);
    ListNode* ptr = list->head;
    ssize_t log_i = 0;
    LIST_FOREACH(*list, ptr, log_i) {
        FPRINTF_(NODE_PREFIX "%zd [" NODE_PARAMS ", label=\" <p>prev = %p | {<i>ptr = %p |", log_i, ptr->prev, ptr);
        if (ptr->elem == ListNode::POISON) {
            FPRINTF_("<e>elem = PZN} | ");
        } else {
            FPRINTF_("<e>elem = " ELEM_T_PRINTF "} | ", ptr->elem);
        }
        FPRINTF_("<n>next = %p}\"", ptr->next);
        FPRINTF_("];\n");
    }
    FPRINTF_(NODE_PREFIX "zero");
    for (log_i = 0; log_i < list->size; log_i++) {
        FPRINTF_("->" NODE_PREFIX "%zd", log_i);
    }
    FPRINTF_(" [weight=10000, color=transparent, arrowtail=none];\n");
    ptr = list->head;
    log_i = 0;
    LIST_FOREACH(*list, ptr, log_i) {
        if (ptr->next != nullptr)
            FPRINTF_(NODE_PREFIX "%zd:<n>->" NODE_PREFIX "%zd:<n> [color=green];\n", log_i, log_i + 1);
        if (ptr->prev != nullptr)
            FPRINTF_(NODE_PREFIX "%zd:<p>->" NODE_PREFIX "%zd:<p> [color=blue];\n", log_i, log_i - 1);
    }
    FPRINTF_("head [shape=rect, label=\"HEAD\", color=yellow, fillcolor=\"#7293ba\",style=filled];\n");
    FPRINTF_("tail [shape=rect, label=\"TAIL\", color=yellow, fillcolor=\"#7293ba\",style=filled];\n");
    FPRINTF_("head->tail[weight=100, color=transparent];");
    FPRINTF_("{rank=same; head; " NODE_PREFIX "0}\n");
    FPRINTF_("{rank=same; tail; " NODE_PREFIX "%zd}\n", list->size - 1);
    FPRINTF_("}\n");
    if (fclose(file) != 0) {
        perror("Error closing file");
        return false;
    }
    str_len = strncat_len(img_filename, log_file.timestamp_dir, log_file.MAX_FILENAME_LEN);
    snprintf(img_filename + str_len, log_file.MAX_FILENAME_LEN - str_len, "%zd", dot_number++);
    str_len = strncat_len(img_filename, ".svg", log_file.MAX_FILENAME_LEN);
    if (!create_img(dot_filename, img_filename)) {
        fprintf(stderr, "Error creating dot graph\n");
        return false;
    }
    return true;
}
References BACKGROUND_COLOR, create_img(), ListNode::elem, ELEM_T_PRINTF, FONT_COLOR, FPRINTF_, List::head, LIST_FOREACH, log_file, LogFileData::MAX_FILENAME_LEN, ListNode::next, NODE_PARAMS, NODE_PREFIX, ListNode::POISON, ListNode::prev, List::size, strncat_len(), List::tail, LogFileData::timestamp_dir, and ZERO_NODE_PARAMS.
Referenced by list_dump().
list_print_error()
void list_print_error (const int err_code)
Prints text error to log by error code.
Parameters
err_code
Definition at line 153 of file dump.cpp.
                                          {
    if (err_code == List::OK) {
        log_printf(&log_file, HTML_TEXT(HTML_GREEN("No error\n")));
    } else {
        PRINT_ERR_(ALREADY_INITIALISED, "Constructor called for already initialised or corrupted list");
        PRINT_ERR_(UNITIALISED, "List is not initialised");
        PRINT_ERR_(INVALID_NODE_PTR, "ListNode pointer is not valid for writing");
        PRINT_ERR_(ALLOC_ERR, "Can't allocate memory");
        PRINT_ERR_(POISON_VAL_FOUND, "There is poison value in list");
        PRINT_ERR_(NEGATIVE_SIZE, "Negative list.size");
        PRINT_ERR_(INVALID_PTR_GIVEN, "Invalid pointer given");
        PRINT_ERR_(DAMAGED_PATH, "List is damaged. Invalid path");
    }
}
References HTML_GREEN, HTML_TEXT, log_file, log_printf(), List::OK, and PRINT_ERR_.
Variable Documentation
log_file
LogFileData log_file [extern]
Definition at line 4 of file main.cpp.
Referenced by list_dump(), list_dump_dot(), list_print_error(), log_close_file(), log_create_timestamp_dir(), log_open_file(), and log_printf().